//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Assimilate.rc
//
#define IDYESTOALL                      3
#define IDNOTOALL                       4
#define IDD_ABOUTBOX                    100
#define IDD_PP_MODEL                    107
#define IDD_PP_SEQUENCE                 108
#define IDD_PP_PROPERTIES               109
#define IDR_MAINFRAME                   128
#define IDR_ASSIMITYPE                  129
#define IDD_ANIMPICKER                  131
#define IDD_DIALOG_YESNOYESNOALL        134
#define IDD_BUILD_ALL                   135
#define IDB_TREEIMAGES                  155
#define IDC_SKIPSTART                   1000
#define IDC_SKIPEND                     1001
#define IDC_TOTFRAMES                   1002
#define IDC_HEADFRAMES                  1003
#define IDC_ORIGINX                     1004
#define IDC_ORIGINY                     1005
#define IDC_ORIGINZ                     1006
#define IDC_TOTSEQUENCES                1007
#define IDC_STARTFRAME                  1008
#define IDC_FRAMECOUNT                  1009
#define IDC_FRAMESPEED                  1010
#define IDC_TARGETFRAME                 1011
#define IDC_STARTFRAME2                 1011
#define IDC_PATH                        1012
#define IDC_ENUM                        1013
#define IDC_LOOPFRAME                   1013
#define IDC_ENUM_BROWSE                 1014
#define IDC_FRAMECOUNT2                 1014
#define IDC_BUFFSIZE                    1015
#define IDC_FRAMESPEED2                 1015
#define IDC_QDATA                       1016
#define IDC_LOOPFRAME2                  1016
#define IDC_QDATA_BROWSE                1017
#define IDC_STARTFRAME3                 1017
#define IDC_QUAKEDIR                    1018
#define IDC_FRAMECOUNT3                 1018
#define IDC_FRAMESPEED3                 1019
#define IDC_LOOPFRAME3                  1020
#define IDC_STARTFRAME4                 1021
#define IDC_FRAMECOUNT4                 1022
#define IDC_FRAMESPEED4                 1023
#define IDC_LOOPFRAME4                  1024
#define IDC_STARTFRAME5                 1025
#define IDC_FRAMECOUNT5                 1026
#define IDC_FRAMESPEED5                 1027
#define IDC_LOOPFRAME5                  1028
#define IDC_BUTTON_CHOOSEANIMATIONENUM  1030
#define IDC_BUTTON_CHOOSEANIMATIONENUM2 1031
#define IDC_BUTTON_CHOOSEANIMATIONENUM3 1032
#define IDC_BUTTON_CHOOSEANIMATIONENUM4 1033
#define IDC_BUTTON_CHOOSEANIMATIONENUM5 1034
#define IDC_LIST_LEGS                   1037
#define IDC_LIST_TORSO                  1038
#define IDC_LIST_BOTH                   1039
#define IDC_EDIT_ANIMATIONENUM          1049
#define IDC_STATIC_COMMENT              1050
#define IDC_EDIT_ANIMATIONENUM2         1050
#define IDC_BUTTON_DEFAULTS             1051
#define IDC_EDIT_ANIMATIONENUM3         1051
#define IDC_EDIT_ANIMATIONENUM4         1052
#define IDC_BUTTON_DEFAULTS_MULTI       1052
#define IDC_EDIT_ANIMATIONENUM5         1053
#define IDC_BUTTON_CLEARANIMATIONENUM   1058
#define IDC_BUTTON_CLEARANIMATIONENUM2  1059
#define IDC_STATIC1                     1059
#define IDC_BUTTON_CLEARANIMATIONENUM3  1060
#define IDC_STATIC2                     1060
#define IDC_CHECK_MULTIPLAYER           1060
#define IDC_BUTTON_CLEARANIMATIONENUM4  1061
#define IDC_STATIC3                     1061
#define IDC_CHECK_SMOOTH_ALL            1061
#define IDC_BUTTON_CLEARANIMATIONENUM5  1062
#define IDC_STATIC4                     1062
#define IDC_STATIC5                     1063
#define IDC_STATIC6                     1064
#define IDC_CHECK_SKEW90                1064
#define IDC_EDIT_SKELPATH               1065
#define IDC_EDIT_ORIGINX                1066
#define IDC_EDIT_ORIGINY                1067
#define IDC_EDIT_BUILDPATH              1067
#define IDC_EDIT_ORIGINZ                1068
#define IDC_CHECK_PREVALIDATECARS       1068
#define IDC_CHECK_MAKESKIN              1069
#define IDC_EDIT_SCALE                  1070
#define IDC_CHECK_GENLOOPFRAME          1071
#define IDC_CHECK_LOSEDUPVERTS          1071
#define IDC_CHECK_KEEPMOTIONBONE        1072
#define IDC_CHECK_MAKESKEL              1073
#define IDC_STATIC_SKELPATH             1074
#define IDC_CHECK_FILTEROUTUSED         1075
#define IDC_CHECK_PREQUAT               1075
#define IDC_LIST_PCJ                    1076
#define IDC_EDIT_PCJ                    1077
#define IDC_BUTTON_PCJ                  1078
#define IDC_BUTTON_DELPCJ               1079
#define IDC_PCJ_STATIC                  1080
#define IDM_ADDFILES                    32771
#define IDM_EXTERNAL                    32772
#define IDM_RESEQUENCE                  32773
#define IDM_PROPERTIES                  32774
#define ID_VIEW_ANIMENUMS               32775
#define ID_VIEW_FRAMEDETAILS            32776
#define IDM_BUILD                       32777
#define IDM_VALIDATE                    32778
#define IDM_BUILD_MULTILOD              32779
#define IDM_VALIDATE_MULTILOD           32780
#define IDM_CARWASH                     32781
#define ID_EDIT_BUILDALL                32782
#define IDM_EDIT_BUILDDEPENDANT         32783
#define ID_VIEW_FRAMEDETAILSONADDITIONALSEQUENCES 32784
#define ID_BUTTON_RESEQUENCE            32785
#define ID_EDIT_LAUNCHMODVIEWONCURRENT  32787

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32789
#define _APS_NEXT_CONTROL_VALUE         1082
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
