code

equ trap_Print								  -1	; CG_PRINT 
equ trap_Error								  -2	; CG_ERROR 
equ trap_Milliseconds						  -3	; CG_MILLISECONDS 
equ trap_PrecisionTimer_Start				  -4	; CG_PRECISIONTIMER_START 
equ trap_PrecisionTimer_End					  -5	; CG_PRECISIONTIMER_END 
equ trap_Cvar_Register						  -6	; CG_CVAR_REGISTER 
equ trap_Cvar_Update						  -7	; CG_CVAR_UPDATE 
equ trap_Cvar_Set							  -8	; CG_CVAR_SET 
equ trap_Cvar_VariableStringBuffer			  -9	; CG_CVAR_VARIABLESTRINGBUFFER 
equ trap_Argc								 -10	; CG_ARGC 
equ trap_Argv								 -11	; CG_ARGV 
equ trap_Args								 -12	; CG_ARGS 
equ trap_FS_FOpenFile						 -13	; CG_FS_FOPENFILE 
equ trap_FS_Read							 -14	; CG_FS_READ 
equ trap_FS_Write							 -15	; CG_FS_WRITE 
equ trap_FS_FCloseFile						 -16	; CG_FS_FCLOSEFILE 
equ trap_FS_GetFileList						 -17	; CG_FS_GETFILELIST 
equ trap_SendConsoleCommand					 -18	; CG_SENDCONSOLECOMMAND 
equ trap_AddCommand							 -19	; CG_ADDCOMMAND 
equ trap_RemoveCommand						 -20	; CG_REMOVECOMMAND 
equ trap_SendClientCommand					 -21	; CG_SENDCLIENTCOMMAND 
equ trap_UpdateScreen						 -22	; CG_UPDATESCREEN 
equ trap_CM_LoadMap							 -23	; CG_CM_LOADMAP 
equ trap_CM_NumInlineModels					 -24	; CG_CM_NUMINLINEMODELS 
equ trap_CM_InlineModel						 -25	; CG_CM_INLINEMODEL 
equ trap_CM_TempBoxModel					 -26	; CG_CM_TEMPBOXMODEL 
equ trap_CM_TempCapsuleModel				 -27	; CG_CM_TEMPCAPSULEMODEL 
equ trap_CM_PointContents					 -28	; CG_CM_POINTCONTENTS 
equ trap_CM_TransformedPointContents		 -29	; CG_CM_TRANSFORMEDPOINTCONTENTS 
equ trap_CM_BoxTrace						 -30	; CG_CM_BOXTRACE 
equ trap_CM_CapsuleTrace					 -31	; CG_CM_CAPSULETRACE 
equ trap_CM_TransformedBoxTrace				 -32	; CG_CM_TRANSFORMEDBOXTRACE 
equ trap_CM_TransformedCapsuleTrace			 -33	; CG_CM_TRANSFORMEDCAPSULETRACE 
equ trap_CM_MarkFragments					 -34	; CG_CM_MARKFRAGMENTS 
equ trap_S_GetVoiceVolume					 -35	; CG_S_GETVOICEVOLUME 
equ trap_S_MuteSound						 -36	; CG_S_MUTESOUND 
equ trap_S_StartSound						 -37	; CG_S_STARTSOUND 
equ trap_S_StartLocalSound					 -38	; CG_S_STARTLOCALSOUND 
equ trap_S_ClearLoopingSounds				 -39	; CG_S_CLEARLOOPINGSOUNDS 
equ trap_S_AddLoopingSound					 -40	; CG_S_ADDLOOPINGSOUND 
equ trap_S_UpdateEntityPosition				 -41	; CG_S_UPDATEENTITYPOSITION 
equ trap_S_AddRealLoopingSound				 -42	; CG_S_ADDREALLOOPINGSOUND 
equ trap_S_StopLoopingSound					 -43	; CG_S_STOPLOOPINGSOUND 
equ trap_S_Respatialize						 -44	; CG_S_RESPATIALIZE 
equ trap_S_RegisterSound					 -45	; CG_S_REGISTERSOUND 
equ trap_S_StartBackgroundTrack				 -46	; CG_S_STARTBACKGROUNDTRACK 
equ trap_S_UpdateAmbientSet					 -47	; CG_S_UPDATEAMBIENTSET 
equ trap_AS_ParseSets						 -48	; CG_AS_PARSESETS 
equ trap_AS_AddPrecacheEntry				 -49	; CG_AS_ADDPRECACHEENTRY 
equ trap_S_AddLocalSet						 -50	; CG_S_ADDLOCALSET 
equ trap_AS_GetBModelSound					 -51	; CG_AS_GETBMODELSOUND 
equ trap_R_LoadWorldMap						 -52	; CG_R_LOADWORLDMAP 
equ trap_R_RegisterModel					 -53	; CG_R_REGISTERMODEL 
equ trap_R_RegisterSkin						 -54	; CG_R_REGISTERSKIN 
equ trap_R_RegisterShader					 -55	; CG_R_REGISTERSHADER 
equ trap_R_RegisterShaderNoMip				 -56	; CG_R_REGISTERSHADERNOMIP 
equ trap_R_RegisterFont						 -57	; CG_R_REGISTERFONT 
equ trap_R_Font_StrLenPixels				 -58	; CG_R_FONT_STRLENPIXELS 
equ trap_R_Font_StrLenChars					 -59	; CG_R_FONT_STRLENCHARS 
equ trap_R_Font_HeightPixels				 -60	; CG_R_FONT_STRHEIGHTPIXELS 
equ trap_R_Font_DrawString					 -61	; CG_R_FONT_DRAWSTRING 
equ trap_Language_IsAsian					 -62	; CG_LANGUAGE_ISASIAN 
equ trap_Language_UsesSpaces				 -63	; CG_LANGUAGE_USESSPACES 
equ trap_AnyLanguage_ReadCharFromString		 -64	; CG_ANYLANGUAGE_READCHARFROMSTRING 
equ trap_R_ClearScene						-201	; CG_R_CLEARSCENE 
equ trap_R_AddRefEntityToScene				-202	; CG_R_ADDREFENTITYTOSCENE 
equ trap_R_AddPolyToScene					-203	; CG_R_ADDPOLYTOSCENE 
equ trap_R_AddPolysToScene					-204	; CG_R_ADDPOLYSTOSCENE 
equ trap_R_LightForPoint					-205	; CG_R_LIGHTFORPOINT 
equ trap_R_AddLightToScene					-206	; CG_R_ADDLIGHTTOSCENE 
equ trap_R_AddAdditiveLightToScene			-207	; CG_R_ADDADDITIVELIGHTTOSCENE 
equ trap_R_RenderScene						-208	; CG_R_RENDERSCENE 
equ trap_R_SetColor							-209	; CG_R_SETCOLOR 
equ trap_R_DrawStretchPic					-210	; CG_R_DRAWSTRETCHPIC 
equ trap_R_ModelBounds						-211	; CG_R_MODELBOUNDS 
equ trap_R_LerpTag							-212	; CG_R_LERPTAG 
equ trap_R_DrawRotatePic					-213	; CG_R_DRAWROTATEPIC 
equ trap_R_DrawRotatePic2					-214	; CG_R_DRAWROTATEPIC2 
equ trap_R_RemapShader						-215	; CG_R_REMAP_SHADER 
equ trap_R_GetLightStyle					-216	; CG_R_GET_LIGHT_STYLE 
equ trap_R_SetLightStyle					-217	; CG_R_SET_LIGHT_STYLE 
equ trap_R_GetBModelVerts					-218	; CG_R_GET_BMODEL_VERTS 
equ trap_FX_AddLine							-219	; CG_FX_ADDLINE 
equ trap_GetGlconfig						-220	; CG_GETGLCONFIG 
equ trap_GetGameState						-221	; CG_GETGAMESTATE 
equ trap_GetCurrentSnapshotNumber			-222	; CG_GETCURRENTSNAPSHOTNUMBER 
equ trap_GetSnapshot						-223	; CG_GETSNAPSHOT 
equ trap_GetDefaultState					-224	; CG_GETDEFAULTSTATE 
equ trap_GetServerCommand					-225	; CG_GETSERVERCOMMAND 
equ trap_GetCurrentCmdNumber				-226	; CG_GETCURRENTCMDNUMBER 
equ trap_GetUserCmd							-227	; CG_GETUSERCMD 
equ trap_SetUserCmdValue					-228	; CG_SETUSERCMDVALUE 
equ trap_SetClientForceAngle				-229	; CG_SETCLIENTFORCEANGLE 
equ trap_SetClientTurnExtent				-230	; CG_SETCLIENTTURNEXTENT 
equ trap_OpenUIMenu							-231	; CG_OPENUIMENU 
equ trap_MemoryRemaining					-234	; CG_MEMORY_REMAINING 
equ trap_Key_IsDown							-235	; CG_KEY_ISDOWN 
equ trap_Key_GetCatcher						-236	; CG_KEY_GETCATCHER 
equ trap_Key_SetCatcher						-237	; CG_KEY_SETCATCHER 
equ trap_Key_GetKey							-238	; CG_KEY_GETKEY 
equ trap_PC_AddGlobalDefine					-239	; CG_PC_ADD_GLOBAL_DEFINE 
equ trap_PC_LoadSource						-240	; CG_PC_LOAD_SOURCE 
equ trap_PC_FreeSource						-241	; CG_PC_FREE_SOURCE 
equ trap_PC_ReadToken						-242	; CG_PC_READ_TOKEN 
equ trap_PC_SourceFileAndLine				-243	; CG_PC_SOURCE_FILE_AND_LINE 
equ trap_PC_LoadGlobalDefines				-244	; CG_PC_LOAD_GLOBAL_DEFINES 
equ trap_PC_RemoveAllGlobalDefines			-245	; CG_PC_REMOVE_ALL_GLOBAL_DEFINES 
equ trap_S_StopBackgroundTrack				-246	; CG_S_STOPBACKGROUNDTRACK 
equ trap_RealTime							-247	; CG_REAL_TIME 
equ trap_SnapVector							-248	; CG_SNAPVECTOR 
equ trap_CIN_PlayCinematic					-249	; CG_CIN_PLAYCINEMATIC 
equ trap_CIN_StopCinematic					-250	; CG_CIN_STOPCINEMATIC 
equ trap_CIN_RunCinematic					-251	; CG_CIN_RUNCINEMATIC 
equ trap_CIN_DrawCinematic					-252	; CG_CIN_DRAWCINEMATIC 
equ trap_CIN_SetExtents						-253	; CG_CIN_SETEXTENTS 
equ trap_GetEntityToken						-254	; CG_GET_ENTITY_TOKEN 
equ trap_R_inPVS							-255	; CG_R_INPVS 
equ trap_FX_RegisterEffect					-256	; CG_FX_REGISTER_EFFECT 
equ trap_FX_PlaySimpleEffect				-257	; CG_FX_PLAY_SIMPLE_EFFECT 
equ trap_FX_PlayEffect						-258	; CG_FX_PLAY_EFFECT 
equ trap_FX_PlayEntityEffect				-259	; CG_FX_PLAY_ENTITY_EFFECT 
equ trap_FX_PlaySimpleEffectID				-260	; CG_FX_PLAY_SIMPLE_EFFECT_ID 
equ trap_FX_PlayEffectID					-261	; CG_FX_PLAY_EFFECT_ID 
equ trap_FX_PlayPortalEffectID				-262	; CG_FX_PLAY_PORTAL_EFFECT_ID 
equ trap_FX_PlayEntityEffectID				-263	; CG_FX_PLAY_ENTITY_EFFECT_ID 
equ trap_FX_PlayBoltedEffectID				-264	; CG_FX_PLAY_BOLTED_EFFECT_ID 
equ trap_FX_AddScheduledEffects				-265	; CG_FX_ADD_SCHEDULED_EFFECTS 
equ trap_FX_InitSystem						-266	; CG_FX_INIT_SYSTEM 
equ trap_FX_FreeSystem						-267	; CG_FX_FREE_SYSTEM 
equ trap_FX_AdjustTime						-268	; CG_FX_ADJUST_TIME 
equ trap_FX_AddPoly							-269	; CG_FX_ADDPOLY 
equ trap_FX_AddBezier						-270	; CG_FX_ADDBEZIER 
equ trap_FX_AddPrimitive					-271	; CG_FX_ADDPRIMITIVE 
equ trap_FX_AddSprite						-272	; CG_FX_ADDSPRITE 
equ trap_FX_AddElectricity					-273	; CG_FX_ADDELECTRICITY 
equ trap_SP_GetStringTextString				-274	; CG_SP_GETSTRINGTEXTSTRING 
equ trap_SP_Register						-275	; CG_SP_REGISTER 
equ trap_ROFF_Clean							-276	; CG_ROFF_CLEAN 
equ trap_ROFF_UpdateEntities				-277	; CG_ROFF_UPDATE_ENTITIES 
equ trap_ROFF_Cache							-278	; CG_ROFF_CACHE 
equ trap_ROFF_Play							-279	; CG_ROFF_PLAY 
equ trap_ROFF_Purge_Ent						-280	; CG_ROFF_PURGE_ENT 
equ trap_TrueMalloc							-281	; CG_TRUEMALLOC 
equ trap_TrueFree							-282	; CG_TRUEFREE 
equ trap_G2_ListModelSurfaces				-283	; CG_G2_LISTSURFACES 
equ trap_G2_ListModelBones					-284	; CG_G2_LISTBONES 
equ trap_G2_SetGhoul2ModelIndexes			-285	; CG_G2_SETMODELS 
equ trap_G2_HaveWeGhoul2Models				-286	; CG_G2_HAVEWEGHOULMODELS 
equ trap_G2API_GiveMeVectorFromMatrix		-287	; CG_G2_GIVEMEVECTORFROMMATRIX 
equ trap_G2API_GetBoltMatrix				-288	; CG_G2_GETBOLT 
equ trap_G2API_GetBoltMatrix_NoReconstruct	-289	; CG_G2_GETBOLT_NOREC 
equ trap_G2API_GetBoltMatrix_NoRecNoRot		-290	; CG_G2_GETBOLT_NOREC_NOROT 
equ trap_G2API_InitGhoul2Model				-291	; CG_G2_INITGHOUL2MODEL 
equ trap_G2API_SetSkin						-292	; CG_G2_SETSKIN 
equ trap_G2API_CollisionDetect				-293	; CG_G2_COLLISIONDETECT 
equ trap_G2API_CleanGhoul2Models			-294	; CG_G2_CLEANMODELS 
equ trap_G2API_SetBoneAngles				-295	; CG_G2_ANGLEOVERRIDE 
equ trap_G2API_SetBoneAnim					-296	; CG_G2_PLAYANIM 
equ trap_G2API_GetBoneAnim					-297	; CG_G2_GETBONEANIM 
equ trap_G2API_GetBoneFrame					-298	; CG_G2_GETBONEFRAME 
equ trap_G2API_GetGLAName					-299	; CG_G2_GETGLANAME 
equ trap_G2API_CopyGhoul2Instance			-300	; CG_G2_COPYGHOUL2INSTANCE 
equ trap_G2API_CopySpecificGhoul2Model		-301	; CG_G2_COPYSPECIFICGHOUL2MODEL 
equ trap_G2API_DuplicateGhoul2Instance		-302	; CG_G2_DUPLICATEGHOUL2INSTANCE 
equ trap_G2API_HasGhoul2ModelOnIndex		-303	; CG_G2_HASGHOUL2MODELONINDEX 
equ trap_G2API_RemoveGhoul2Model			-304	; CG_G2_REMOVEGHOUL2MODEL 
equ trap_G2API_AddBolt						-305	; CG_G2_ADDBOLT 
equ trap_G2API_SetBoltInfo					-306	; CG_G2_SETBOLTON 
equ trap_G2API_SetRootSurface				-307	; CG_G2_SETROOTSURFACE 
equ trap_G2API_SetSurfaceOnOff				-308	; CG_G2_SETSURFACEONOFF 
equ trap_G2API_SetNewOrigin					-309	; CG_G2_SETNEWORIGIN 
equ trap_G2API_GetSurfaceRenderStatus		-310	; CG_G2_GETSURFACERENDERSTATUS 
equ trap_G2API_GetTime						-311	; CG_G2_GETTIME 
equ trap_G2API_SetTime						-312	; CG_G2_SETTIME 
equ trap_G2API_SetRagDoll					-313	; CG_G2_SETRAGDOLL 
equ trap_G2API_AnimateG2Models				-314	; CG_G2_ANIMATEG2MODELS 
equ trap_G2API_SetBoneIKState				-315	; CG_G2_SETBONEIKSTATE 
equ trap_G2API_IKMove						-316	; CG_G2_IKMOVE 
equ trap_G2API_GetSurfaceName				-317	; CG_G2_GETSURFACENAME 
equ trap_CG_RegisterSharedMemory			-318	; CG_SET_SHARED_BUFFER 
equ trap_CM_RegisterTerrain					-319	; CG_CM_REGISTER_TERRAIN 
equ trap_RMG_Init							-320	; CG_RMG_INIT 
equ trap_RE_InitRendererTerrain				-321	; CG_RE_INIT_RENDERER_TERRAIN 
equ trap_R_WeatherContentsOverride			-322	; CG_R_WEATHER_CONTENTS_OVERRIDE 


; hardcoded functions
equ memset									-101	; CGAME_MEMSET 
equ memcpy									-102	; CGAME_MEMCPY 
equ strncpy									-103	; CGAME_STRNCPY 
equ sin										-104	; CGAME_SIN 
equ cos										-105	; CGAME_COS 
equ atan2									-106	; CGAME_ATAN2 
equ sqrt									-107	; CGAME_SQRT 
equ matrixmultiply							-108	; CGAME_MATRIXMULTIPLY 
equ anglevectors							-109	; CGAME_ANGLEVECTORS 
equ perpendicularvector						-110	; CGAME_PERPENDICULARVECTOR 
equ floor									-111	; CGAME_FLOOR 
equ ceil									-112	; CGAME_CEIL 
equ acos									-115	; CGAME_ACOS 
equ asin									-116	; CGAME_ASIN 
