/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-release-2.30.6-0-gba2f78a00 (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-release-2.30.6-0-gba2f78a00"
#endif
#define SDL_REVISION_NUMBER 0
