set(CMAKE_SYSTEM_NAME "Linux")
set(CMAKE_SYSTEM_PROCESSOR "x86_64")

set(COMPILER_PREFIX "clang")

set(CMAKE_C_COMPILER ${COMPILER_PREFIX} CACHE STRING "C compiler")
set(CMAKE_CXX_COMPILER ${COMPILER_PREFIX}++ CACHE STRING "C++ compiler")

set(CMAKE_C_COMPILER_ARG1 -m64)
set(CMAKE_CXX_COMPILER_ARG1 -m64)
