typedef enum //# characters_e
{
	//HazTeam Alpha
	//CHARACTER_MUNRO = 0,
	CHARACTER_FOSTER = 0,
	CHARACTER_TELSIA,
	CHARACTER_BIESSMAN,
	CHARACTER_CHANG,
	CHARACTER_CHELL,
	CHARACTER_JUROT,
	//HazTeam Beta
	CHARACTER_LAIRD,
	CHARACTER_KENN,
	CHARACTER_OVIEDO,
	CHARACTER_ODELL,
	CHARACTER_NELSON,
	CHARACTER_JAWORSKI,
	CHARACTER_CSATLOS,
	//Senior Crew
	CHARACTER_JANEWAY,
	CHARACTER_CHAKOTAY,
	CHARACTER_TUVOK,
	CHARACTER_TUVOKHAZ,
	CHARACTER_TORRES,
	CHARACTER_PARIS,
	CHARACTER_KIM,
	CHARACTER_DOCTOR,
	CHARACTER_SEVEN,
	CHARACTER_SEVENHAZ,
	CHARACTER_NEELIX,
	//Other Crew
	CHARACTER_PELLETIER,
	//Generic Crew
	CHARACTER_CREWMAN,
	//CHARACTER_ENSIGN,
	CHARACTER_LT,
	CHARACTER_COMM,
	CHARACTER_CAPT,
	CHARACTER_GENERIC1,
	CHARACTER_GENERIC2,
	CHARACTER_GENERIC3,
	CHARACTER_GENERIC4,
	//# #eol
	CHARACTER_NUM_CHARS
} characters_t;

typedef struct
{
	char	*name;
	char	*sound;
	sfxHandle_t		soundIndex;
} characterName_t;
