//Siege class def file.
//NOTE: light version used for Star Destroyer map

ClassInfo
{
	name			"Imperial Pilot"
	weapons		WP_BLASTER_PISTOL
	maxhealth		25
	maxarmor		0
	startarmor		0
	model			"stormpilot" 				//this is optional, if it's here it forces the model to this.
	skin			"default"					//this is optional, if it's here it forces the skin to this.
	uishader		"models/players/stormpilot/icon_default"
	class_shader	"gfx/mp/c_icon_infantry"
}

description	
"@SIEGE_INF_IMP_PILOT"
