//Siege class def file.

ClassInfo
{
	name			"Mercenary"
	weapons			WP_BLASTER_PISTOL|WP_BLASTER|WP_REPEATER|WP_TRIP_MINE
	forcepowers		0
	maxhealth		100
	startarmor		0
	model			"human_merc" 					//this is optional, if it's here it forces the model to this.
	skin			"default"					//this is optional, if it's here it forces the skin to this.
	uishader		"models/players/human_merc/icon_default"
	holdables		HI_SENTRY_GUN
	class_shader	"gfx/mp/c_icon_infantry"
}

description	"@SIEGE_INF_MERCENARY"
