//Siege class def file.
//NOTE: light version used for Star Destroyer map

ClassInfo
{
	name			"Rebel Pilot"
	weapons		WP_BLASTER_PISTOL
	maxhealth		25
	maxarmor		0
	model			"rebel_pilot" 				//this is optional, if it's here it forces the model to this.
	skin			"default"					//this is optional, if it's here it forces the skin to this.
	uishader		"models/players/rebel_pilot/icon_default"
	class_shader	"gfx/mp/c_icon_infantry"
}

description	
"@SIEGE_INF_REB_PILOT"
